# -*- coding: utf-8 -*-
"""AluraStoreLatam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19kUQo0TUpByfxa7QsXhiZ4qlE-kBDwxX

### Importación de datos
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

"""#1. Análisis de facturación


"""

ingreso_tienda = tienda['Precio'].sum()
ingreso_tienda2 = tienda2['Precio'].sum()
ingreso_tienda3 = tienda3['Precio'].sum()
ingreso_tienda4 = tienda4['Precio'].sum()

print("--- Ingresos Totales por Tienda ---")
print(f"Tienda 1: ${ingreso_tienda:,.2f}")
print(f"Tienda 2: ${ingreso_tienda2:,.2f}")
print(f"Tienda 3: ${ingreso_tienda3:,.2f}")
print(f"Tienda 4: ${ingreso_tienda4:,.2f}")

"""# 2. Ventas por categoría"""

ventas_cat_tienda = tienda['Categoría del Producto'].value_counts()
ventas_cat_tienda2 = tienda2['Categoría del Producto'].value_counts()
ventas_cat_tienda3 = tienda3['Categoría del Producto'].value_counts()
ventas_cat_tienda4 = tienda4['Categoría del Producto'].value_counts()

print("--- 🛍️ Tienda 1: Ventas por Categoría ---")
print(ventas_cat_tienda)
print("\n" + "---" * 15)

print("--- 🛍️ Tienda 2: Ventas por Categoría ---")
print(ventas_cat_tienda2)
print("\n" + "---" * 15)

print("--- 🛍️ Tienda 3: Ventas por Categoría ---")
print(ventas_cat_tienda3)
print("\n" + "---" * 15)

print("--- 🛍️ Tienda 4: Ventas por Categoría ---")
print(ventas_cat_tienda4)

"""# 3. Calificación promedio de la tienda

"""

calif_promedio_tienda = tienda['Calificación'].mean()
calif_promedio_tienda2 = tienda2['Calificación'].mean()
calif_promedio_tienda3 = tienda3['Calificación'].mean()
calif_promedio_tienda4 = tienda4['Calificación'].mean()

print("--- ⭐ Calificación Promedio por Tienda ---")
print(f"Tienda 1: {calif_promedio_tienda:.2f} estrellas")
print(f"Tienda 2: {calif_promedio_tienda2:.2f} estrellas")
print(f"Tienda 3: {calif_promedio_tienda3:.2f} estrellas")
print(f"Tienda 4: {calif_promedio_tienda4:.2f} estrellas")

"""# 4. Productos más y menos vendidos"""

ventas_prod_tienda = tienda['Producto'].value_counts()
ventas_prod_tienda2 = tienda2['Producto'].value_counts()
ventas_prod_tienda3 = tienda3['Producto'].value_counts()
ventas_prod_tienda4 = tienda4['Producto'].value_counts()

# --- Tienda 1 ---
print("--- 🥇 Tienda 1: Productos Destacados ---")
print("\n📈 MÁS Vendidos (Top 5):")
print(ventas_prod_tienda.head(5))
print("\n📉 MENOS Vendidos (Bottom 5):")
print(ventas_prod_tienda.tail(5))
print("\n" + "---" * 15)

# --- Tienda 2 ---
print("--- 🥇 Tienda 2: Productos Destacados ---")
print("\n📈 MÁS Vendidos (Top 5):")
print(ventas_prod_tienda2.head(5))
print("\n📉 MENOS Vendidos (Bottom 5):")
print(ventas_prod_tienda2.tail(5))
print("\n" + "---" * 15)

# --- Tienda 3 ---
print("--- 🥇 Tienda 3: Productos Destacados ---")
print("\n📈 MÁS Vendidos (Top 5):")
print(ventas_prod_tienda3.head(5))
print("\n📉 MENOS Vendidos (Bottom 5):")
print(ventas_prod_tienda3.tail(5))
print("\n" + "---" * 15)

# --- Tienda 4 ---
print("--- 🥇 Tienda 4: Productos Destacados ---")
print("\n📈 MÁS Vendidos (Top 5):")
print(ventas_prod_tienda4.head(5))
print("\n📉 MENOS Vendidos (Bottom 5):")
print(ventas_prod_tienda4.tail(5))

"""# 5. Envío promedio por tienda"""

costo_prom_tienda = tienda['Costo de envío'].mean()
costo_prom_tienda2 = tienda2['Costo de envío'].mean()
costo_prom_tienda3 = tienda3['Costo de envío'].mean()
costo_prom_tienda4 = tienda4['Costo de envío'].mean()

print("--- 🚚 Costo de Envío Promedio por Tienda ---")
print(f"Tienda 1: ${costo_prom_tienda:,.2f}")
print(f"Tienda 2: ${costo_prom_tienda2:,.2f}")
print(f"Tienda 3: ${costo_prom_tienda3:,.2f}")
print(f"Tienda 4: ${costo_prom_tienda4:,.2f}")

"""# 6. Gráfico de Barras: Comparación de Ingresos por Tienda"""

ingresos = {
    'Tienda': ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4'],
    'Ingreso Total': [ingreso_tienda, ingreso_tienda2, ingreso_tienda3, ingreso_tienda4]
}
df_ingresos = pd.DataFrame(ingresos)

plt.figure(figsize=(8, 5))
sns.barplot(x='Tienda', y='Ingreso Total', data=df_ingresos, palette='viridis')
plt.title('Ingreso Total Generado por Cada Tienda')
plt.ylabel('Ingreso Total (en millones)')
plt.xlabel('Tienda')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""# 7. Gráfico Circular: Distribución de Categorías"""

ventas_cat_tienda_top = ventas_cat_tienda.head(5)
otras = ventas_cat_tienda.iloc[5:].sum()

ventas_cat_tienda2_top = ventas_cat_tienda2.head(5)
otras_2 = ventas_cat_tienda2.iloc[5:].sum()

ventas_cat_tienda3_top = ventas_cat_tienda3.head(5)
otras_3 = ventas_cat_tienda3.iloc[5:].sum()

ventas_cat_tienda4_top = ventas_cat_tienda4.head(5)
otras_4 = ventas_cat_tienda4.iloc[5:].sum()

if otras > 0:
    ventas_cat_tienda_final = pd.concat([ventas_cat_tienda_top, pd.Series(otras, index=['Otras'])])
else:
    ventas_cat_tienda_final = ventas_cat_tienda_top

if otras_2 > 0:
    ventas_cat_tienda2_final = pd.concat([ventas_cat_tienda2_top, pd.Series(otras_2, index=['Otras'])])
else:
    ventas_cat_tienda2_final = ventas_cat_tienda2_top

if otras_3 > 0:
    ventas_cat_tienda3_final = pd.concat([ventas_cat_tienda3_top, pd.Series(otras_3, index=['Otras'])])
else:
    ventas_cat_tienda3_final = ventas_cat_tienda3_top

if otras_4 > 0:
    ventas_cat_tienda4_final = pd.concat([ventas_cat_tienda4_top, pd.Series(otras_4, index=['Otras'])])
else:
    ventas_cat_tienda4_final = ventas_cat_tienda4_top

plt.figure(figsize=(7, 7))
plt.pie(
    ventas_cat_tienda_final.values,
    labels=ventas_cat_tienda_final.index,
    autopct='%1.1f%%',
    startangle=90,
    wedgeprops={'edgecolor': 'black'}
)
plt.title('Distribución Porcentual de Ventas por Categoría (Tienda 1)')
plt.show()

plt.figure(figsize=(7, 7))
plt.pie(
    ventas_cat_tienda2_final.values,
    labels=ventas_cat_tienda2_final.index,
    autopct='%1.1f%%',
    startangle=90,
    wedgeprops={'edgecolor': 'black'}
)
plt.title('Distribución Porcentual de Ventas por Categoría (Tienda 2)')
plt.show()

plt.figure(figsize=(7, 7))
plt.pie(
    ventas_cat_tienda3_final.values,
    labels=ventas_cat_tienda3_final.index,
    autopct='%1.1f%%',
    startangle=90,
    wedgeprops={'edgecolor': 'black'}
)
plt.title('Distribución Porcentual de Ventas por Categoría (Tienda 3)')
plt.show()

plt.figure(figsize=(7, 7))
plt.pie(
    ventas_cat_tienda4_final.values,
    labels=ventas_cat_tienda4_final.index,
    autopct='%1.1f%%',
    startangle=90,
    wedgeprops={'edgecolor': 'black'}
)
plt.title('Distribución Porcentual de Ventas por Categoría (Tienda 4)')
plt.show()

"""# 8. Gráfico de Puntos/Dispersión: Costo vs. Calificación"""

plt.figure(figsize=(8, 6))
sns.scatterplot(
    x=tienda4['Costo de envío'],
    y=tienda4['Calificación'],
    hue=tienda4['Categoría del Producto'],
    data=tienda4,
    palette='tab10',
    alpha=0.6,
    s=50
)
plt.title('Relación entre el Costo de Envío y la Calificación del Cliente (Tienda 4)')
plt.xlabel('Costo de Envío')
plt.ylabel('Calificación del Cliente')
plt.legend(title='Categoría', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

"""#Informe de Recomendación Estratégica: Venta de Tienda para el Sr. Juan

##Introducción y Objetivo del Análisis

El presente informe tiene como finalidad sintetizar los hallazgos clave obtenidos del análisis de los datos de transacciones de cuatro tiendas (Tienda 1 a Tienda 4). El objetivo principal es determinar cuál de las tiendas representa la mejor opción para ser vendida por el Sr. Juan, considerando todos los factores de rendimiento, crecimiento potencial, reputación del cliente y eficiencia operativa.

El análisis se centró en cinco métricas críticas: Ingresos Totales, Satisfacción del Cliente (Calificación Promedio), Mix de Productos (Categorías más vendidas), Productos Estrella y Costos de Envío.

##I. Análisis de Métricas Clave

####A. Rentabilidad y Escala (Ingresos Totales)

La métrica de ingresos es fundamental para establecer el precio de venta de un activo, reflejando su valor actual de mercado.


"""

data_ingresos = {
        'Tienda': ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4'],
        'Ingreso Total': [ingreso_tienda, ingreso_tienda2, ingreso_tienda3, ingreso_tienda4]
    }
df_ingresos = pd.DataFrame(data_ingresos).sort_values(by='Ingreso Total', ascending=False)
    # Asignar posición basado en el ordenamiento
df_ingresos['Posición'] = [f'{i+1}º' for i in range(len(df_ingresos))]
df_ingresos = df_ingresos.reset_index(drop=True)

print("--- A. Rentabilidad y Escala (Ingresos Totales) ---")
print(df_ingresos.to_string(index=False, formatters={'Ingreso Total': '${:,.2f}'.format}))

"""**Hallazgo Clave:**
La Tienda 1 es la líder en generación de ingresos ($1,150,880,400.00).

Esto la convierte en la más valiosa para un comprador enfocado en el volumen. La Tienda 4 es el activo de menor rendimiento ($1,038,375,700.00).

####B. Reputación y Satisfacción (Calificación Promedio)

La calificación promedio refleja la salud de la marca y la fidelidad del cliente a largo plazo, métricas críticas para la valoración de la marca.
"""

calif_promedio_tienda = tienda['Calificación'].mean()
calif_promedio_tienda2 = tienda2['Calificación'].mean()
calif_promedio_tienda3 = tienda3['Calificación'].mean()
calif_promedio_tienda4 = tienda4['Calificación'].mean()

data_calificacion = {
        'Tienda': ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4'],
        'Calificación Promedio': [calif_promedio_tienda, calif_promedio_tienda2, calif_promedio_tienda3, calif_promedio_tienda4]
    }
df_calificacion = pd.DataFrame(data_calificacion)
print("--- B. Reputación y Satisfacción (Calificación Promedio) ---")

df_calificacion = df_calificacion.set_index('Tienda').reindex(['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4']).reset_index()
print(df_calificacion.to_string(index=False, formatters={'Calificación Promedio': '{:.2f}'.format}))

"""Hallazgo Clave: La Tienda 3 demuestra la mayor calidad percibida (4.05 estrellas), lo que reduce el riesgo para un posible comprador. La Tienda 1 presenta la peor calificación (3.98), que no termina de ser determinante para indicar que existan problemas de satisfacción o calidad del producto.

####C. Eficiencia y Mix de Producto (Categorías y Costos)

La distribución de ventas por categoría revela el enfoque de cada tienda.
"""

costo_prom_tienda = tienda['Costo de envío'].mean()
costo_prom_tienda2 = tienda2['Costo de envío'].mean()
costo_prom_tienda3 = tienda3['Costo de envío'].mean()
costo_prom_tienda4 = tienda4['Costo de envío'].mean()

categoria_dominante_1 = tienda['Categoría del Producto'].value_counts().idxmax()
categoria_dominante_2 = tienda2['Categoría del Producto'].value_counts().idxmax()
categoria_dominante_3 = tienda3['Categoría del Producto'].value_counts().idxmax()
categoria_dominante_4 = tienda4['Categoría del Producto'].value_counts().idxmax()

data_operaciones = {
        'Tienda': ['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4'],
        'Categoría Dominante': [categoria_dominante_1, categoria_dominante_2, categoria_dominante_3, categoria_dominante_4],
        'Costo de Envío Promedio': [costo_prom_tienda, costo_prom_tienda2, costo_prom_tienda3, costo_prom_tienda4]
    }
df_operaciones = pd.DataFrame(data_operaciones)

print("--- C. Eficiencia y Mix de Producto (Categorías y Costos) ---")

df_operaciones = df_operaciones.set_index('Tienda').reindex(['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4']).reset_index()
print(df_operaciones.to_string(index=False, formatters={'Costo de Envío Promedio': '${:,.2f}'.format}))

"""Análisis Operacional:

Tienda 1 tiene el costo de envío más alto ($26,018.61), lo que, junto con su calificación de 3.98, sugiere que para los clientes no es tan determinante el costo de envío frente al promedio de valoración mas allá de reducir solo un poco la satisfacción (3.98).

La Tienda 4 tiene el costo de envío más bajo ($23,459.46), lo que se acompaña con una calificación de (4.00), lo que indica que el bajo costo no necesariamente determinala percepción de la calidad del producto o servicio percibido.

#II. Recomendación Final
La decisión de venta se enfoca en maximizar el capital de salida para el Sr. Juan. Por lo tanto, se recomienda vender el activo de mayor valor y rendimiento comprobado.

##Recomendación Específica:

Se recomienda al Sr. Juan vender la Tienda 1.

##Justificación Detallada

La decisión de vender la Tienda 1 se justifica en que presenta la combinación de valor más atractiva para un comprador a gran escala, basado en los siguientes hallazgos:

Liderazgo en Ingresos (Maximización del Precio): Al ser la 1ª en Ingresos Totales (superando los $1.15 Mil Millones), la Tienda 1 garantiza el precio de venta más alto y un retorno de la inversión inmediato y significativo para el Sr. Juan.

Activo Más Valioso: Como se indicó en el análisis, es la tienda "más valiosa para un comprador enfocado en el volumen". Venderla capitaliza esta posición dominante en el mercado.

Demanda Inelástica (Tolerancia a Costos): A pesar de tener el Costo de Envío más alto ($26,018.61) y la calificación más baja (3.98), sigue siendo la líder absoluta en ingresos. Esto demuestra una demanda robusta y una base de clientes que valora los productos de la tienda por encima de los costos adicionales o las pequeñas fricciones en la satisfacción.


##Contrarrecomendación:

Vender la Tienda 4, el activo de menor rendimiento ($1.03B), representaría la menor entrada de capital. Si bien la Tienda 4 tiene costos de envío bajos y una calificación decente (4.00), venderla no cumple el objetivo de maximizar el capital de salida.

Al vender la Tienda 1, el Sr. Juan capitaliza su activo más valioso en su punto máximo, asegurando una entrada de capital significativamente mayor que puede ser reinvertida para optimizar las operaciones de las tiendas restantes (como la Tienda 3, con la mejor calificación, y la Tienda 4, con los costos de envío más bajos).

#Análisis del desempeño geográfico
## 1. Unificar los Datos
Para comparar, primero debemos unificar los DataFrames.
Añadimos una columna 'Tienda' a cada uno ANTES de unirlos.
"""

tienda['Tienda'] = 'Tienda 1'
tienda2['Tienda'] = 'Tienda 2'
tienda3['Tienda'] = 'Tienda 3'
tienda4['Tienda'] = 'Tienda 4'

df_total = pd.concat([tienda, tienda2, tienda3, tienda4], ignore_index=True)

print("--- DataFrame Unificado Creado (primeras 5 filas) ---")
print(df_total.sample(1000))
print("\n" + "---" * 15 + "\n")

"""##2. Visualización 1: Huella Geográfica por Tienda"""

print("Generando Gráfico 1: Huella Geográfica por Tienda...")
plt.figure(figsize=(10, 8))
sns.scatterplot(
    data=df_total.sample(1000),
    x='lon',
    y='lat',
    hue='Tienda',  # Color diferente para cada tienda
    palette='deep',  # Paleta de colores vibrante
    alpha=0.5,     # Transparencia para ver superposiciones (densidad)
    s=50           # Tamaño del punto
)
plt.title('Distribución Geográfica de Ventas por Tienda', fontsize=16)
plt.xlabel('Longitud (lon)', fontsize=12)
plt.ylabel('Latitud (lat)', fontsize=12)
plt.legend(title='Tienda', loc='upper right', bbox_to_anchor=(1.25, 1))
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout() # Ajusta el gráfico para que la leyenda no se corte
plt.show()

"""##3. Visualización 2: Análisis Geográfico de Ingresos"""

print("Generando Gráfico 2: Distribución de Ingresos (Precio)...")
plt.figure(figsize=(10, 8))
sns.scatterplot(
    data=df_total.sample(1000),
    x='lon',
    y='lat',
    size='Precio',      # El tamaño del punto representa el ingreso
    hue='Precio',       # El color también representa el ingreso
    palette='viridis',  # Paleta 'viridis' (amarillo=alto, azul=bajo)
    sizes=(20, 500),    # Rango de tamaños de los puntos
    alpha=0.6
)
plt.title('Distribución Geográfica de Ingresos (Tamaño y Color = Precio)', fontsize=16)
plt.xlabel('Longitud (lon)', fontsize=12)
plt.ylabel('Latitud (lat)', fontsize=12)
plt.legend(title='Precio', loc='upper right', bbox_to_anchor=(1.25, 1))
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""## 4. Visualización 3: Análisis Geográfico de Calificaciones de Clientes"""

print("Generando Gráfico 3: Distribución de Calificaciones...")
plt.figure(figsize=(10, 8))
sns.scatterplot(
    data=df_total.sample(1000),
    x='lon',
    y='lat',
    hue='Calificación', # El color representa la calificación
    palette='coolwarm_r', # Paleta 'coolwarm' (Rojo=Bajo, Azul=Alto)
    alpha=0.7,
    s=50
)
plt.title('Distribución Geográfica de Calificaciones de Clientes', fontsize=16)
plt.xlabel('Longitud (lon)', fontsize=12)
plt.ylabel('Latitud (lat)', fontsize=12)
plt.legend(title='Calificación', loc='upper right', bbox_to_anchor=(1.3, 1))
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

print("\n--- Análisis Geográfico Completo ---")